### ISSUE TITLE
`-s` timeout may be too short

### ISSUE THREAD

**Issue by job** [jenfrie/byz-rpki#1]
Hi!

Super cool that you created this, I've thought a few times about experimenting in this space.

In the README I noticed `rpki-client  ... -s 60 ...` - 60 seconds really is way shorter than you'd probably want in normal operations.

Some background:

The default timeout is 60 minutes. The `rpki-client` design is based on the assumption that there is a 1 hour budget to complete all the work (fetching & validating). After 60 minutes the program will kill itself and exit with a non-zero exit error code, because if it wasn't able to complete all the work in that time, something is wrong and manual investigation is probably warranted.

To ensure that the program finishes it's work within 60 minutes, the following time box limits are imposed:

* Each repository can take up to 1/4th of $timeout (15 minutes in the default case, or 15 seconds in your case) to complete synchronization. If the synchronization work is not completed within that 1/4th, the connection is killed. If the connection was RRDP, a second job is scheduled to attempt to synchronize via RSYNC. Again, this RSYNC process will be allowed 1/4th of 60 minutes to complete, and is killed after that.
* All ongoing network synchronization work is halted after 3/4th of the $timeout (45 minutes with default settings, in your case 45 seconds). This 'global time limit' on network synchronization exists to mitigate certain forms of abuse.
* The remaining 1/4th of $timeout is spend on any outstanding cryptographic validation work and writing out the JSON file.

Setting the `-s` timeout too low might result in the program being unable to successfully finish, because there simply is more work to be done than can fit in the CPU in the time allotted for it.

I recommend running with the default timer :-)

**Comment by jenfrie** [comment]
Hi Job,

I appreciate the feedback!

I didn't notice I still had this in the Readme. I had originally noted it down for testing purposes, so I could see the log output for normal operation and when rpki-client times out.

The actual command being run in the container has higher (more appropriate) timeouts configured in the Dockerfile. (I think 1 or 2 hours).

In any case, thank you for reaching out!

-------- Original Message --------

**Comment by job** [comment]
The trick to get results “fast” out of the system is to run `rpki-client` in a loop, start it again a few seconds after it finished. The timeout option probably shouldn’t be used by most people at all.

Cheers! Look forward to learn more about this project
